# Sample Appveyor file from https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci
build: off
environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix:
    - ARCH: x86_64
    - ARCH: i386


before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-%ARCH%
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test --ghc-options -v3
